
DROP DATABASE IF EXISTS viveros;

CREATE DATABASE IF NOT EXISTS viveros;

START TRANSACTION;

DROP TABLE IF EXISTS VIVERO;

/* Crear Tabla 'VIVERO' */

CREATE TABLE IF NOT EXISTS VIVERO (
    NOMBRE VARCHAR(30) NOT NULL,
    LOCALIDAD VARCHAR(30) NULL,
    LATITUD FLOAT NULL,
    LONGITUD FLOAT NULL,
    PRIMARY KEY (NOMBRE)
);

DROP TABLE IF EXISTS ZONA;

/* Crear Tabla 'ZONA' */

CREATE TABLE IF NOT EXISTS ZONA (
  NOMBRE VARCHAR(30) NOT NULL,
  VIVERO_NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY (NOMBRE),
  CONSTRAINT fk_ZONA_VIVERO
    FOREIGN KEY (VIVERO_NOMBRE)
    REFERENCES VIVERO (NOMBRE)
    ON DELETE CASCADE
    ON UPDATE CASCADE );

DROP TABLE IF EXISTS PRODUCTO;

/* Crear Tabla 'PRODUCTO' */

CREATE TABLE IF NOT EXISTS PRODUCTO (
  ID_PRODUCTO VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(30) NULL,
  PRECIO FLOAT NULL,
  STOCK INT NULL,
  PRIMARY KEY (ID_PRODUCTO));

DROP TABLE IF EXISTS CLIENTE;

/* Crear Tabla 'CLIENTE' */

CREATE TABLE IF NOT EXISTS CLIENTE (
  DNI VARCHAR(9) NOT NULL,
  BONUS FLOAT NULL,
  NUM_NUM_PEDIDOS INT NULL,
  PRIMARY KEY (DNI));

DROP TABLE IF EXISTS EMPLEADO;

/* Crear Tabla 'EMPLEADO' */

CREATE TABLE IF NOT EXISTS EMPLEADO (
  DNI VARCHAR(9) NOT NULL,
  SUELDO FLOAT NOT NULL,
  ANTIGUEDAD INT NULL,
  FECHA_INI TIMESTAMP NULL,
  FECHA_FIN TIMESTAMP NULL,
  VENTAS INT NULL,
  ZONA_NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY (DNI),
  CONSTRAINT fk_EMPLEADO_ZONA1
    FOREIGN KEY (ZONA_NOMBRE)
    REFERENCES ZONA (NOMBRE)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


DROP TABLE IF EXISTS PRODUCTO_ZONA;

/* Crear Tabla 'PRODUCTO_ZONA' */

CREATE TABLE IF NOT EXISTS PRODUCTO_ZONA (
  ID_PRODUCTO VARCHAR(20) NOT NULL,
  ZONA_NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_PRODUCTO, ZONA_NOMBRE),
  CONSTRAINT fk_PRODUCTO_ZONA_PRODUCTO1
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PRODUCTO_ZONA_ZONA1
    FOREIGN KEY (ZONA_NOMBRE)
    REFERENCES ZONA (NOMBRE)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


DROP TABLE IF EXISTS COMPRA;

/* Crear Tabla 'COMPRA' */

CREATE TABLE IF NOT EXISTS COMPRA (
  PRODUCTO_COD_PROD VARCHAR(20) NOT NULL,
  CLIENTE_DNI VARCHAR(9) NOT NULL,
  FECHA TIMESTAMP NOT NULL,
  CANTIDAD INT NULL,
  EMPLEADO_DNI VARCHAR(9) NOT NULL,
  PRIMARY KEY (PRODUCTO_COD_PROD, CLIENTE_DNI, FECHA),
  CONSTRAINT fk_COMPRA_PRODUCTO
    FOREIGN KEY (PRODUCTO_COD_PROD)
    REFERENCES PRODUCTO (ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPRA_CLIENTE
    FOREIGN KEY (CLIENTE_DNI)
    REFERENCES CLIENTE (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPRA_EMPLEADO
    FOREIGN KEY (EMPLEADO_DNI)
    REFERENCES EMPLEADO (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

COMMIT;

/* Introducir Datos Tabla 'VIVERO' */

START TRANSACTION;
INSERT INTO VIVERO (NOMBRE, LOCALIDAD, LATITUD, LONGITUD) VALUES ('Vivero_1', 'La Laguna', 28.483402, -16.304390);
INSERT INTO VIVERO (NOMBRE, LOCALIDAD, LATITUD, LONGITUD) VALUES ('Vivero_2', 'Tegueste', 28.523708, -16.340421);
INSERT INTO VIVERO (NOMBRE, LOCALIDAD, LATITUD, LONGITUD) VALUES ('Vivero_3', 'Buenavista', 28.375164, -16.850060);
INSERT INTO VIVERO (NOMBRE, LOCALIDAD, LATITUD, LONGITUD) VALUES ('Vivero_4', 'Arona', 28.098280, -16.677871);
INSERT INTO VIVERO (NOMBRE, LOCALIDAD, LATITUD, LONGITUD) VALUES ('Vivero_5', 'Radazul', 28.404713, -16.320063);

COMMIT;

/* Introducir Datos Tabla 'ZONA' */

START TRANSACTION;
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_1', 'Vivero_1');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_2', 'Vivero_2');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_3', 'Vivero_3');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_4', 'Vivero_3');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_5', 'Vivero_4');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_6', 'Vivero_5');
INSERT INTO ZONA (NOMBRE, VIVERO_NOMBRE) VALUES ('Zona_7', 'Vivero_5');

COMMIT;

/* Introducir Datos Tabla 'PRODUCTO' */

START TRANSACTION;
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00101', 'Azucena', 78, 7.85);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00102', 'Margarita', 86, 2.56);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00103', 'Lirio', 105, 6.00);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00104', 'Rosa', 78, 1.25);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00105', 'Tulipan', 212, 6.99);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00106', 'Orquidea', 23, 12.86);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00107', 'Amapola', 98, 9.99);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK) VALUES ('00108', 'Geranio', 145, 17.63);

COMMIT;

/* Introducir Datos Tabla 'CLIENTE' */

START TRANSACTION;
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('11111111A', 20, 2);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('22222222B', 44, 5);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('33333333C', 32.5, 3);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('44444444D', 8, 1);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('55555555E', 17.5, 1);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('66666666F', 25, 3);
INSERT INTO CLIENTE (DNI, BONUS, NUM_PEDIDOS) VALUES ('77777777G', 34, 2);

COMMIT;
