/* Crear Tabla 'VIVERO' */

CREATE TABLE IF NOT EXISTS VIVERO (
  NOMBRE VARCHAR(30) NOT NULL,
  LOCALIDAD VARCHAR(30) NULL,
  LATITUD FLOAT NULL,
  LONGITUD FLOAT NULL,
  PRIMARY KEY (NOMBRE));


/* Crear Tabla 'ZONA' */

CREATE TABLE IF NOT EXISTS ZONA (
  NOMBRE VARCHAR(30) NOT NULL,
  VIVERO_NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY (NOMBRE),
  CONSTRAINT fk_ZONA_VIVERO
    FOREIGN KEY (VIVERO_NOMBRE)
    REFERENCES VIVERO (NOMBRE)
    ON DELETE CASCADE
    ON UPDATE CASCADE );


/* Crear Tabla 'PRODUCTO' */

CREATE TABLE IF NOT EXISTS PRODUCTO (
  ID_PRODUCTO VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(30) NULL,
  STOCK INT NULL,
  PRECIO FLOAT NULL,
  PRIMARY KEY (ID_PRODUCTO));


/* Crear Tabla 'CLIENTE' */

CREATE TABLE IF NOT EXISTS CLIENTE (
  DNI VARCHAR(9) NOT NULL,
  BONIFICACION FLOAT NULL,
  TOTAL_MENSUAL INT NULL,
  PRIMARY KEY (DNI));


/* Crear Tabla 'EMPLEADO' */


CREATE TABLE IF NOT EXISTS EMPLEADO (
  DNI VARCHAR(9) NOT NULL,
  SUELDO FLOAT NULL,
  ANTIGUEDAD INT NULL,
  FECHA_INI TIMESTAMP NULL,
  FECHA_FIN TIMESTAMP NULL,
  VENTAS INT NULL,
  ZONA_NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY (DNI),
  CONSTRAINT fk_EMPLEADO_ZONA1
    FOREIGN KEY (ZONA_NOMBRE)
    REFERENCES ZONA (NOMBRE)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


